version: "3.8"

services:
  postgres:
    image: postgres
    container_name: backend-project-postgres-container
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      # - postgres-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
