// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package main

import (
	"database/sql"
)

type File struct {
	ID          int32
	Name        sql.NullString
	Description sql.NullString
	Type        sql.NullString
	FilePath    sql.NullString
}

type FilesTag struct {
	FileID sql.NullInt32
	TagID  sql.NullInt32
}

type Tag struct {
	ID   int32
	Name sql.NullString
}
